//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiCarSharing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adres
    {
        public int AdresId { get; set; }
        public int UserId { get; set; }
        public string AdresTanimi { get; set; }
        public string Adres1 { get; set; }
        public string Ulke { get; set; }
        public string Sehir { get; set; }
        public string Ilce { get; set; }
        public string Tel { get; set; }
    
        public virtual UyeBilgi UyeBilgi { get; set; }
    }
}
