//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiCarSharing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resim
    {
        public int ResimId { get; set; }
        public int AracId { get; set; }
        public string ResimYol { get; set; }
        public string Onay { get; set; }
    
        public virtual Arac Arac { get; set; }
    }
}
