//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiCarSharing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yolculuk
    {
        public int YolculukId { get; set; }
        public int AracSahipId { get; set; }
        public int KiralayanId { get; set; }
        public int AracId { get; set; }
        public string Yorum { get; set; }
    
        public virtual UyeBilgi UyeBilgi { get; set; }
        public virtual UyeBilgi UyeBilgi1 { get; set; }
    }
}
